services:
  express1:
    build: ./microservice1
    container_name: express1
    ports: 
      - 3001:3000
    volumes:
      - ./microservice1:/home/node/express
    depends_on: 
      - rabbitmq
  express2:
    build: ./microservice2
    container_name: express2
    ports: 
      - 3002:3000
    volumes:
      - ./microservice2:/home/node/express
    depends_on: 
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin